version: '3.5'

services:

  influxdb2:
    restart: always
    image: influxdb:2.2.0
    container_name: influxdb2
    hostname: influxdb2
    networks:
      - functest
    ports:
      - "8086:8086"
    # volumes:
    #   - type: bind
    #     source: ./influxdb2/data
    #     target: /var/lib/influxdb2
    #   - type: bind
    #     source: ./influxdb2/config
    #     target: /etc/influxdb2
    # environment:
    #   - DOCKER_INFLUXDB_INIT_MODE=setup
    #   - DOCKER_INFLUXDB_INIT_USERNAME=admin
    #   - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    #   - DOCKER_INFLUXDB_INIT_ORG=FuncTestOrg
    #   - DOCKER_INFLUXDB_INIT_BUCKET=FuncTestBucket
    #   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=FuncTestToken
    #   - DOCKER_INFLUXDB_INIT_RETENTION=0

  grafana:
    restart: always
    image: grafana/grafana:8.5.0
    container_name: grafana
    hostname: grafana
    networks:
      - functest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb2

networks:
  functest:
